config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users, skip: [:registration]
  root 'pins#index'
  get 'home/about'
  
  

end

app/models/pin.rb
class Pin < ActiveRecord::Base
    belongs_to :user
    has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permited_parameters, if: :devise_controller?
  
protected

  def configure_permited_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:userName])
    devise_parameter_sanitizer.permit(:account_update, keys: [:userName])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
    
  end 
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all.order('created_at DESC').paginate(:page => params[:page], :per_page => 5)
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build( pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

def correct_user
  @pin = current_user.pins.find_by(id: params[:id])
  redirect_to pins_path, notice: 'Not authorized to update this pin' if @pin.nil?
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Pinterested', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to 'Pins', pins_path %></li>

        <% if user_signed_in? %>
          <li><%= link_to '+', new_pin_path %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
        <% end %>
      <li><%=link_to 'About', home_about_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/_jumbo.html.erb
<div class="jumbotron center ">
    <h1>Pinterested - like</h1>
    <p><3</p>
        <% if user_signed_in? %>
         <%= link_to 'Pins', pins_path, class: 'btn btn-primary'%>
         <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-default'%>
        <% else %>
            <%= link_to 'Login', new_user_session_path, class: 'btn btn-primary'%> 
        <% end %>
</div>

app/views/home/about.html.erb
<h1>About.</h1>

app/views/home/index.html.erb
<div class="jumbotron center ">
    <h1>Welcome page.</h1>
    <p>Find me in app/views/home/index.html.erb</p>
        <% if user_signed_in? %>
         <%= link_to 'Pins', pins_path, class: 'btn btn-primary'%>
         <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-default'%>
        <% else %>
            <%= link_to 'Login', new_user_session_path, class: 'btn btn-primary'%> 
            <%= link_to 'Sign Up', new_user_registration_path , class: 'btn btn-default'%>
        <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails 101</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1'>
</head>
<body>

<%= render 'home/header' %> 

<div class='container'>
  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: 'alert alert-info') %>
  <% end %>
  <%= yield %>  
</div>


</body>
</html>

app/views/pins/_form.html.erb
<%= form_for @pin, html: {multipart: true} do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %><br> 
    <%= f.text_field :description, class: 'form-control ' %>
  </div>
  
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: 'form-control ' %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h1>Editing Pin</h1></div>
    <div class="panel-body">
        <%= render 'form' %>
    </div>
    
    <div class="panel-footer">
        <%= link_to 'Show', @pin %> |
        <%= link_to 'Back', pins_path %>
    </div>
</div>

app/views/pins/index.html.erb
<%= render 'home/jumbo' unless user_signed_in?  %>
<div id='pins-container' class='transitions-enabled'>
  <% @pins.each do |pin| %>
  <div class='box'>
    <div class="panel panel-default">
      <div class="panel-heading"><h4><%= pin.description %></h4></div>
      <div class="panel-body">
        <br><%= link_to image_tag(pin.image.url(:medium)) , pin %></br>
        <p><strong>By: <%= pin.user.userName if pin.user  %></strong></p>
      </div>
      <% if pin.user == current_user %>
      <div class="panel-footer">
        <%= link_to 'Edit', edit_pin_path(pin) %> |  
        <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
      <% end %> 
      
    </div>
  </div>
  <% end %>
</div> 
 <div class='center'>
<%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h1>New Pin</h1></div> 
      <div class="panel-body">
        <%= render 'form' %>
    </div>
    <div class="panel-footer">
        <%= link_to 'Back', pins_path %>
    </div>
</div>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-offset-2 col-md-8 ">
    <div class='panel panel-default'>
      <div class='panel-heading center'><%= image_tag @pin.image.url(:medium) %></br></div>
        <div class='panel-body'>
        <p>
          <%= @pin.description %>
        </p>
        <p><strong>By: </strong><%= @pin.user.userName if @pin.user  %>
        </div>
        <div class="panel-footer">
          <% if @pin.user == current_user %>
          <%= link_to 'Edit', edit_pin_path(@pin) %> |
          <% end %>
          <%= link_to 'Back', pins_path %>
        </div>
      </div>
    </div>
  </div>